---
sidebar: sidebar 
permalink: task-add-s3-bucket.html 
keywords: s3 buckets, s3 storage, s3 working environment, s3 system, amazon s3 buckets, amazon s3 working environment, amazon s3 system, netapp console 
summary: システム ページで Amazon S3 システムが利用可能になると、 NetAppコンソールから直接バケットを追加できます。 
---
= S3バケットを追加する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Amazon S3 システムが [システム] ページで利用可能になると、 NetAppコンソールから直接バケットを追加できます。

.手順
. [_システム_] ページで、Amazon S3 システムをダブルクリックして [_Amazon S3 バケットの概要_] ページを表示し、[*バケットの追加*] をクリックします。
+
_バケットの追加_ ページが表示されます。

. _バケットの追加_ページで、バケットを作成するために必要な情報を入力し、*適用*をクリックします。
+
.. バケットに使用する名前を入力します。
.. バケットの所有者となる AWS アカウントを選択します。これは、コンソールエージェントが展開されたプライマリアカウント、または https://docs.netapp.com/us-en/console-setup-admin/task-adding-aws-accounts.html#add-credentials-to-a-connector["NetAppコンソールに追加した別のアカウント"^]。
.. バケットが作成される AWS リージョンを選択します。
.. オプションで、バケットで S3 オブジェクトロックを有効にして、Write Once Read Many (WORM) モデルを使用してオブジェクトを保存できます。オブジェクト ロックを使用する予定の場合は、バケットの作成時に有効にする必要があります。オブジェクト ロックを有効にすると、バージョン管理も有効になります。 https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html["Amazon S3 ドキュメントからオブジェクトロックの詳細をご覧ください"^] 。
+
バケットが作成されます。





.次の手順
バケットを最初に追加するときに、バージョン管理、タグ、または暗号化を手動で構成することはできません。バケットを作成した後、バケットのその他のプロパティを構成できます。link:task-change-s3-bucket-settings.html["バケット設定の変更について詳しくは"] 。
